/*   BAC_CONS.C
 ------------------------------------------------------------------------------
|
|    Property of  :   ABB Verkehrssysteme AG, CH-8050 ZÅrich / Switzerland
|    COPYRIGHT    :   (c) 1992 ABB Verkehrssysteme AG
|                     
 ------------------------------------------------------------------------------
|
|    Project      :   T C N   B U S   A D M I N I S T R A T O R
|
 ------------------------------------------------------------------------------
|                     
|    File Name    :   BAC_CONS.C
|
|    Document     :
|                     
|    Abstract     :   MVB Event Poll
|
|    Remarks      :
|
|    Dependencies :
|
|    Accepted     :
|
 ------------------------------------------------------------------------------
|
|    HISTORY:
|
|    Vers  Dept.   YY-MM-DD  State    Name    Reference
|    ----  ------  --------  -------  ------- ---------
|      1   BAEI-2  93-01-11  created  Marsden
|
 ------------------------------------------------------------------------------
*/


#ifndef    BAC_CONS_H
#define    BAC_CONS_H

#include   "baa_auxi.h"
#include   "bap_poll.h"

extern const struct BAA_STR_PDT baa_pdt;
extern const struct  BAP_STR_TRANS_TAB bap_trans[512];

#endif
