/*

cs
  1. August 1996,  8:39
*/
/****************************************************************
*  AAA   BBBB   BBBB   |                                        *
* A   A  B   B  B   B  |                 wtb.h                  *
* AAAAA  BBBB   BBBB   |                                        *
* A   A  B   B  B   B  |                                        *
* A   A  BBBB   BBBB   |       TRAIN COMMUNICATION NETWORK      *
*                      |                                        *
*  ASEA BROWN BOVERI   |      Copyright 1996 by ABB Henschel    *
*----------------------+----------------------------------------*
*                                                               *
* author   :  Schaefers                                         *
* version  :  1.0                                               *
* date     :  01.08.96                                          *
*                                                               *
*-------------------------------------------------------------- *
*                                                               *
*                general exported WTB definitions               *
*                                                               *
*-------------------------------------------------------------- *
*  changes:                                                     *
*                                                               *
* version    date    name  reason                               *
* -------  --------  ----  ------                               *
* 1.0      01.08.96  cs    creation                             *
****************************************************************/
#ifndef WTB_H
#define WTB_H
/*
 * definition of general constants
 */
#define WTB_ADR_MIN                         0x01
#define WTB_ADR_MASTER                      0x01
#define WTB_ADR_MAX                         0x3F
#define WTB_ADR_UNNAMED                     0x7F
#define WTB_ADR_BROADCAST                   0xFF
#define WTB_ADR_MIDDLE                      0x1F
/*
 * definition of standard types
 */
#endif
