/***********************************************************************/
/* Questo file e' stato generato automaticamente dal comando checkmod  */
/***********************************************************************/
    "-MT-",
/***********************************************************************/

/******************************************************************************/
/* I seguenti file risultano modificati rispetto alla copia depositata in CVS */
/******************************************************************************/
/*
   .\A\HW\SRC\brdSetup.c
   .\SRC\atr_hw.h
*/

/****************************************************************/
/* I seguenti file risultano con tag diverso da rel_06a */
/****************************************************************/
/*
   .\A\HW\SRC\c16x.h  (work_schiavor)
   .\SRC\hw_mon.c  (work_schiavor)
   .\SRC\atr_hw.h  (work_schiavor)
*/
