/*=====================================================================================*/
/* File added for WTB compatibility                                                    */
/* Header file (pd_hand.h)         													   */
/* 																					   */
/* Version 1.0																		   */
/*																					   */
/* (c)1998 Ansaldo Trasporti														   */
/* Written by Giuseppe Carnevale													   */
/*=====================================================================================*/

#include "pd_jdp.h"

