                        atr_nma.mod
/*======================================================================*/
                        \SW\TCN\ATR\atr_nma.c
/*======================================================================*/
/* ATR TCN Network Management extensions                                                                                                    */
/* (c)1997 Ansaldo Trasporti														            */
/* Written by Giuseppe Carnevale													            */
/*======================================================================*/                                                                                                          */
1.0 (17/04/97): first release
1.1 (21/05/97): write_ext_ncdb_objects() modified into write_ext_ncdb_object(),
                atr_nma_call() do not return the Network Management header
1.2 (04/06/98): added XMODEM NCDB transfer
1.3 (14/09/98): the flash addresses are parameters
1.40    Ven.18.feb.2000         Napoli                  Mungi
        - Si eliminano inutili include am29f040.h e crc.h
        - Si applicano le regole di editing ATR\ISV

/*======================================================================*/
                        \SW\TCN\ATR\atr_nma.h
/*======================================================================*/
/* ATR TCN Network Management extensions											            */
/* (c)1997 Ansaldo Trasporti														            */
/* Written by Giuseppe Carnevale													            */
/*==============================================================================================*/
1.0 (??/??/97): ???
1.1 (??/??/9?): ???
1.2 (??/??/9?): ???
1.3 (17/03/99): ???

