/*=====================================================================================*/
/* File added for WTB compatibility                                                    */
/* Header file (pil.h)          													   */
/* 																					   */
/* Version 1.0																		   */
/*																					   */
/* (c)1998 Ansaldo Trasporti														   */
/* Written by Giuseppe Carnevale													   */
/*=====================================================================================*/

#include "pi_sys.h"

/* The following inclusion is needed by the WTB link layer */
#include "md_layer.h"

