/********************************************************************************
*Sab.14.feb.04           v.1.00          \sw_st\sw_stb\tststbxx\header\tstmvb.h *
*********************************************************************************
* Header per Routine per test del MVB BUS                                       *
*********************************************************************************
********************************************************************************/
short tstmvb_txrx(short argc, char *argv[] );
short test_mvb (short argc, char *argv[] );
short test_SW1 (short argc, char *argv[] );
void MVB_init (void);
short t_mvbel_stim(void);
