@ECHO OFF

PATH C:\MRI\LICENSE;C:\MRI\mcc68k;C:\mri\asm68k;C:\mri\master\mon68k;C:\master\bin;c:\TMP
rem PATH %PATH%;C:\MRI\LICENSE;C:\MRI\mcc68k;C:\mri\asm68k;C:\mri\master\mon68k;C:\master\bin;c:\TMP

SET XRAYMASTER=C:\MRI\MASTER
SET USR_MRI=C:\MRI\MCC68K
SET SPECTRA=C:\MASTER

SET MAKESTARTUP=C:\MASTER\ETC\STARTUP.MK
SET MRI_MAKE=DMAKE -E

SET MRI_68K_BIN=C:\MRI\MCC68K;C:\MRI\ASM68K
SET MRI_68K_INC=C:\MRI\MCC68K;C:\MASTER\TARGET\INCLUDE
SET MRI_68K_LIB=C:\MRI\MCC68K\68020
SET MRI_68K_TMP=C:\TMP
SET MON68K=C:\MRI\MASTER\MON68K
                           

dmake
